Update build.rs
filecoin-project/ff pull request #6
Opened 2020-05-07 06:57 UTC by LuoZijun

fix compilation error on arm platform.

2020-05-07 14:50 UTC, dignifiedquire requested changes
this breaks because it does not respect the target architecture

2020-05-07 14:54 UTC, LuoZijun commented
> this breaks because it does not respect the target architecture

humm, change `[target.'cfg(target_arch = "x86_64")'.build-dependencies]` to `[build-dependencies]` ?

2020-05-08 13:19 UTC, dignifiedquire commented on build.rs
> -    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
You need to use this env flag, to read out the target_arch properly. This should not be deleted

2020-05-18 02:05 UTC, LuoZijun commented
@dignifiedquire Sorry for delay.

*Cargo.toml*:
```toml
[target.'cfg(target_arch = "x86_64")'.build-dependencies]
cc = "1.0.50"
```

*build.rs*:
```rust
fn main() {
    let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    if target_arch == "x86_64" {
        // NOTE: crate `cc` should usable on any arch.
        //       so replace `[target.'cfg(target_arch = "x86_64")'.build-dependencies]`
        //       to `[build-dependencies]` can fix build-dependenchy on some non-x86 arch.
        cc::Build::new()
            .flag("-c")
            .file("./asm/mul_4.S")
            .compile("libff-derive-crypto.a");
    }
}
```

2020-07-24 00:31 UTC, closed without merging